In [147]:
import pandas as pd
import numpy as np

## Analisis exploratorio 

In [148]:
df = pd.read_csv("2023.1_Sysarmy_Encuesta de remuneracin salarial Argentina.csv", encoding="utf-8")
print(df.head())

  estoy_trabajando_en           donde_estas_trabajando dedicacion  \
0           Argentina                     Buenos Aires  Full-Time   
1           Argentina  Ciudad Autónoma de Buenos Aires  Full-Time   
2           Argentina  Ciudad Autónoma de Buenos Aires  Full-Time   
3           Argentina  Ciudad Autónoma de Buenos Aires  Full-Time   
4           Argentina                        Río Negro  Full-Time   

            tipo_de_contrato  \
0  Staff (planta permanente)   
1  Staff (planta permanente)   
2  Staff (planta permanente)   
3  Staff (planta permanente)   
4  Staff (planta permanente)   

   ultimo_salario_mensual_o_retiro_bruto_en_tu_moneda_local  \
0                                           475480.0          
1                                           260000.0          
2                                           106350.0          
3                                           339000.0          
4                                           380000.0          

  ultimo_sala

In [149]:
df.info()
df.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5767 entries, 0 to 5766
Data columns (total 50 columns):
 #   Column                                                                                Non-Null Count  Dtype  
---  ------                                                                                --------------  -----  
 0   estoy_trabajando_en                                                                   5767 non-null   object 
 1   donde_estas_trabajando                                                                5767 non-null   object 
 2   dedicacion                                                                            5767 non-null   object 
 3   tipo_de_contrato                                                                      5767 non-null   object 
 4   ultimo_salario_mensual_o_retiro_bruto_en_tu_moneda_local                              5767 non-null   float64
 5   ultimo_salario_mensual_o_retiro_neto_en_tu_moneda_local                            

estoy_trabajando_en           donde_estas_trabajando dedicacion  \
0           Argentina                     Buenos Aires  Full-Time   
1           Argentina  Ciudad Autónoma de Buenos Aires  Full-Time   
2           Argentina  Ciudad Autónoma de Buenos Aires  Full-Time   
3           Argentina  Ciudad Autónoma de Buenos Aires  Full-Time   
4           Argentina                        Río Negro  Full-Time   

            tipo_de_contrato  \
0  Staff (planta permanente)   
1  Staff (planta permanente)   
2  Staff (planta permanente)   
3  Staff (planta permanente)   
4  Staff (planta permanente)   

   ultimo_salario_mensual_o_retiro_bruto_en_tu_moneda_local  \
0                                           475480.0          
1                                           260000.0          
2                                           106350.0          
3                                           339000.0          
4                                           380000.0          

  ultimo_salario_mensual_o_retiro_neto_en_tu_moneda_local  \
0                                             396346        
1                                             220000        
2                                              88560        
3                                             283700        
4                                             320000        

                                    pagos_en_dolares  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4  Mi sueldo está dolarizado (pero cobro en moned...   

  si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron  \
0                                                NaN                            
1                                                NaN                            
2                                                NaN                            
3                                                NaN                            
4                                                179                            

  pagos_en_criptomonedas que_porcentaje_o_monto_recibis_en_criptomonedas  ...  \
0                    NaN                                             NaN  ...   
1                    NaN                                             NaN  ...   
2                    NaN                                             NaN  ...   
3                    NaN                                             NaN  ...   
4                    NaN                                             NaN  ...   

  salir_o_seguir_contestando_sobre_las_guardias tenes_guardias  \
0                                           NaN            NaN   
1                                           NaN            NaN   
2                                           NaN            NaN   
3                             Terminar encuesta             No   
4                                           NaN            NaN   

  cuanto_cobras_por_guardia         porcentajebruto_o_neto  \
0                       NaN                            NaN   
1                       NaN                            NaN   
2                       NaN                            NaN   
3                       0.0  Porcentaje de mi sueldo bruto   
4                       NaN                            NaN   

  salir_o_seguir_contestando_sobre_estudios  tengo_edad me_identifico_genero  \
0                                       NaN          25            Varón Cis   
1                                       NaN          27            Mujer Cis   
2                                       NaN          21            Varón Cis   
3              Responder sobre mis estudios          25            Varón Cis   
4                                       NaN          24            Varón Cis   

   sueldo_dolarizado    seniority me_id_extra  
0              False  Semi-Senior  Hom

## Imprimo % de null y blancos y las variables de cada columna

In [150]:
# Calcular porcentaje de valores nulos por columna
porcentaje_nulos = df.isna().mean() * 100

# Calcular porcentaje de valores en blanco por columna
porcentaje_blancos = df.apply(lambda col: col.astype(str).str.strip().eq('')).mean() * 100

# Calcular número de variables distintas por columna (sin contar NaN ni blancos)
num_variables = df.apply(lambda col: col.dropna().astype(str).str.strip().replace('', pd.NA).dropna().nunique())

# Combinar todo en un solo DataFrame resumen
resumen = pd.DataFrame({
    'Porcentaje_Nulos': porcentaje_nulos.round(2),
    'Porcentaje_Blancos': porcentaje_blancos.round(2),
    'Num_Variables': num_variables
})
print (resumen)

                                                    Porcentaje_Nulos  \
estoy_trabajando_en                                             0.00   
donde_estas_trabajando                                          0.00   
dedicacion                                                      0.00   
tipo_de_contrato                                                0.00   
ultimo_salario_mensual_o_retiro_bruto_en_tu_mon...              0.00   
ultimo_salario_mensual_o_retiro_neto_en_tu_mone...              3.64   
pagos_en_dolares                                               73.11   
si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo...             82.94   
pagos_en_criptomonedas                                         96.97   
que_porcentaje_o_monto_recibis_en_criptomonedas                86.30   
recibis_algun_tipo_de_bono                                      0.00   
a_que_esta_atado_el_bono                                        0.00   
tuviste_actualizaciones_de_tus_ingresos_laboral...              

In [151]:
# Seleccionar la columna
columna = 'trabajo_de'
serie = df[columna].astype(str).str.strip()

# Eliminar valores en blanco y NaN
serie_limpia = serie.replace('', pd.NA).dropna()

# Contar frecuencia de cada variable
frecuencia = serie_limpia.value_counts()

# Mostrar resultado
print(f"Desglose de la columna '{columna}':")
print(frecuencia)

Desglose de la columna 'trabajo_de':
trabajo_de
Developer                  2219
SysAdmin / DevOps / SRE     534
Technical Leader            359
QA / Tester                 241
Manager / Director          207
                           ... 
Key account manager           1
IT Governance Head            1
Ecommerce Manager             1
AV tech                       1
IT Risk & Compliance          1
Name: count, Length: 354, dtype: int64


Controlar que tipo de valores tiene la columna pago_dolares para analizar con que reemplazar null

In [152]:
df["pagos_en_dolares"].dtype

# Ver algunos ejemplos de valores
df["pagos_en_dolares"].unique()

array([nan, 'Mi sueldo está dolarizado (pero cobro en moneda local)',
       'Cobro parte del salario en dólares',
       'Cobro todo el salario en dólares'], dtype=object)

In [153]:
df["pagos_en_dolares"] = df["pagos_en_dolares"].fillna('No dolarizado / Sin dato')

 Elimino columnas que tiene alto % de null y que no concidero relevantes para mi analisis

In [154]:
df.drop("que_porcentaje_o_monto_recibis_en_criptomonedas", axis=1, inplace=True)

quiero ver la columna maximo nivel de estudios porque concidero relevante para mi analisis

In [155]:
df["maximo_nivel_de_estudios"].dtype

# Ver algunos ejemplos de valores
df["maximo_nivel_de_estudios"].unique()

array([nan, 'Universitario', 'Terciario', 'Secundario',
       'Posgrado/Especialización', 'Maestría', 'Doctorado',
       'Posdoctorado'], dtype=object)

reemplazo los NAN por sin estudios/sin dato para estandarizar

In [156]:
df["maximo_nivel_de_estudios"] = df["maximo_nivel_de_estudios"].fillna('sin estudios / Sin dato')

hago lo mismo con la colmna estados 

In [157]:
df["estado"].dtype

# Ver algunos ejemplos de valores
df["estado"].unique()

array([nan, 'En curso', 'Completo', 'Incompleto'], dtype=object)

In [158]:
df["estado"] = df["estado"].fillna('Sin dato')

In [159]:
df["universidad"].dtype

# Ver algunos ejemplos de valores
df["universidad"].unique()

array([nan, 'UP - Universidad de Palermo',
       'UTN - Universidad Tecnológica Nacional',
       'UAI - Universidad Abierta Interamericana',
       'UBA - Universidad de Buenos Aires',
       'ESBA - Escuela Superior Buenos Aires',
       'UNQ - Universidad Nacional de Quilmes',
       'UNLP - Universidad Nacional de La Plata', 'Escuela Da Vinci',
       'ISSD - Instituto Superior Santo Domingo',
       'UM - Universidad de Morón',
       'IUA - Instituto Universitario Aeronáutico',
       'UNSAM - Universidad de San Martín',
       'UNC - Universidad Nacional de Córdoba',
       'UADE - Universidad Argentina De la Empresa',
       'Universidad Siglo 21', 'UNCUYO - Universidad Nacional de Cuyo',
       'UNGS - Universidad Nacional de General Sarmiento',
       'UNLaM - Universidad Nacional de La Matanza', 'ORT',
       'UNNNE - Universidad Nacional del Nordeste',
       'UB - Universidad de Belgrano', 'UBP - Universidad Blas Pascal',
       'UNR - Universidad Nacional de Rosario',
  

In [160]:
df["universidad"] = df["universidad"].fillna('Sin dato')

In [161]:
df["pagos_en_criptomonedas"].dtype

# Ver algunos ejemplos de valores
df["pagos_en_criptomonedas"].unique()

array([nan, 'Cobro todo el salario criptomonedas',
       'Cobro parte del salario criptomonedas'], dtype=object)

In [162]:
df["pagos_en_criptomonedas"] = df["pagos_en_criptomonedas"].fillna('Sin dato')

In [163]:
df["si_participaste_de_un_boot_campque_carrera_estudiaste"].dtype

# Ver algunos ejemplos de valores
df["si_participaste_de_un_boot_campque_carrera_estudiaste"].unique()

array([nan, 'fullstack', 'fullstack nodejs + front', 'Product Management',
       'Aceleración Alkemy',
       'diplomatura en usabilidad y accesibilidad, diplomatura en UX, diplomatura en UX research, UX avanzado',
       'Tecnicatura en Sistemas', 'Full Stack Developer Javascript',
       'Full Stack Developer', 'Data science', 'Front End Developer',
       'Product Designer', 'Fullstack', 'Full Stack Java Web',
       'Full stack development', 'Java developer', 'Aceleración C#',
       'Desarrollo de Aplicaciones Web en .NET',
       'Certified Tech Developer CTD', 'No', 'Backend developer',
       'Desarrollo web fullstack con Javascript',
       'No participé en ningún bootcamp', 'Desarrollo Front End',
       'Full Stack', 'Full stack Developer', 'Big Data',
       'Programación en Front con Reac', 'Fullstack developer',
       'The Web Developer Bootcamp (de Colt Steele) en Udemy. React, Hooks y Redux en ui.dev',
       'Full stack con Python', 'devops y desarrollo fullstack',
 

In [164]:
df["si_participaste_de_un_boot_campque_carrera_estudiaste"] = df["si_participaste_de_un_boot_campque_carrera_estudiaste"].fillna('Sin dato')

In [165]:
df["participaste_de_algun_boot_camp"].dtype

# Ver algunos ejemplos de valores
df["participaste_de_algun_boot_camp"].unique()

array([nan, 'no', 'En la misma empresa que estoy, ITR', 'No', 'acamica',
       'Mujeres en Tecnología', 'Alkemy', 'UTN, UFLO, UB, Coder house',
       'Informatorio', 'Si', 'Plataforma 5',
       'no, pero vi que en las universidades les falta una unmdp! (nacional de mardel) :)',
       'HENRY', 'FAMAF', 'Alura LATAM', 'Uxopedia', 'Digital House',
       'ComIT', 'Henry', 'Comunidad IT (ComIT)', 'Digital house',
       'Potrero Digital', 'CoderHouse', 'SoyHenry', 'Codo a Codo',
       'Codo a codo', 'Le Wagon', 'Udemy y ui.dev', '111mil',
       'digital house y platzi', 'GlobalLogic', 'Educacion IT', 'Platzi',
       'baufest', 'Ada ITW', 'Udacity', 'NUCBA', 'NO', 'ADA',
       'Coderhouse', 'ADA ITW', 'Si, ADA.',
       'Mindhub (Por el gobierno de la ciudad)', 'Mindhub',
       'No, hice muchos cursos de Udemy', 'Met, Coderhouse',
       'No, me parecen un engańo la mayoría de ellos.',
       'Polo Tecnologico La Rioja', 'ITBA', 'Open BootCamp',
       'Academia Numen / Codo a Codo

In [166]:
df["participaste_de_algun_boot_camp"] = df["participaste_de_algun_boot_camp"].fillna('Sin dato')

elimino columnas que no me sirven a mi analisis

In [167]:
df.drop(['si_tu_sueldo_esta_dolarizado_cual_fue_el_ultimo_valor_del_dolar_que_tomaron', 'tenes_guardias', 'salir_o_seguir_contestando_sobre_estudios'], axis=1, inplace=True)

In [168]:
nulos = df.isna().sum().reset_index()
nulos.columns = ['columna', 'cantidad_nulos']
nulos['porcentaje'] = (nulos['cantidad_nulos'] / len(df)) * 100
nulos.sort_values(by='porcentaje', ascending=False, inplace=True)
print(nulos)

                                              columna  cantidad_nulos  \
40                             porcentajebruto_o_neto            4028   
39                          cuanto_cobras_por_guardia            4028   
34                                            carrera            3226   
38      salir_o_seguir_contestando_sobre_las_guardias            3113   
11               de_que_fue_el_ajuste_total_acumulado             910   
5   ultimo_salario_mensual_o_retiro_neto_en_tu_mon...             210   
45                                        me_id_extra             200   
26                                         qa_testing               5   
22       plataformas_que_utilizas_en_tu_puesto_actual               2   
24  frameworksherramientas_y_librerias_que_utilice...               1   
25                                     bases_de_datos               1   
1                              donde_estas_trabajando               0   
3                                    tipo_de_contra

In [169]:
df.drop(['cuanto_cobras_por_guardia', 'salir_o_seguir_contestando_sobre_las_guardias'], axis=1, inplace=True)

In [171]:
df.to_csv('datos_limpios.csv', index=False, encoding='utf-8')